[window]
	opacity = 0.75
	padding = { x = 10, y = 10 } 

[font]
	normal = { family = "SauceCodeProNerdFont", style = "Semibold" }
	size = 11.5

[cursor]
	style = { shape = "Beam", blinking = "On"}

[colors.primary]
	background = "#000505"
